# Generated by Django 5.1.2 on 2024-10-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_note_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
