# Generated by Django 5.1.2 on 2024-11-05 22:53

import Apps.Rolplay.GameApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/rolplay/games_app/games/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Apps.Rolplay.GameApp.models.get_image_upload_path),
        ),
    ]
