# Generated by Django 5.1.2 on 2025-02-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
