# Generated by Django 5.1.2 on 2025-04-02 12:12

import Apps.Rolplay.GameApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_note_completed_alter_note_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default=Apps.Rolplay.GameApp.models.get_random_default_character_image, null=True, upload_to='images/rolplay/games_app/character/images')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='files/rolplay/game_app/character/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='GameApp.game')),
            ],
        ),
    ]
