# Generated by Django 5.1.2 on 2025-04-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0003_alter_diary_description_alter_game_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
