# Generated by Django 5.1.2 on 2025-04-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0004_character_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/excel/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
