# Generated by Django 5.1.2 on 2025-04-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0005_alter_character_excel_file_alter_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='files/rolplay/game_app/character/'),
        ),
    ]
